---
version: 3

images:
  base_image:
    name: registry.access.redhat.com/ubi9/python-312:latest

dependencies:
  galaxy: galaxy_requirements.yml
  python: pip_requirements.txt
  system: bindep.txt

  python_interpreter:
    python_path: /usr/bin/python3.12

  ansible_core:
    package_pip: ansible-core==2.20.1

  ansible_runner:
    package_pip: ansible-runner>=2.4.0

  exclude:
    system:
      - openshift-clients
      - qemu-img

additional_build_files:
  - src: ansible.cfg
    dest: configs
  - src: run.sh
    dest: scripts
  - src: pip_requirements.txt
    dest: requirements

additional_build_steps:
  prepend_base:
    - USER root
    - RUN $PYCMD -V
    - RUN $PYCMD -m pip -V
    - RUN $PYCMD -m pip install -U pip setuptools wheel

  append_base:
    - |
      RUN if ! id -u runner >/dev/null 2>&1; then \
        useradd -u 1000 -g 0 -d /home/runner -m runner; \
      fi
    - |
      RUN echo "==== FULL REQUIREMENTS ====" && cat /tmp/src/requirements.txt
    - |
      RUN echo "==== XMLTODICT LINES ====" && grep -n xmltodict /tmp/src/requirements.txt || true

  prepend_final:
    - COPY --from=quay.io/ansible/receptor:latest /usr/bin/receptor /usr/bin/receptor
    - USER root
    - RUN mkdir -p /var/run/receptor && chown 1000:0 /var/run/receptor
    - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg
    - COPY _build/scripts/run.sh /run.sh
    - COPY _build/requirements/pip_requirements.txt /tmp/pip_requirements.txt
    - RUN chmod +x /run.sh

  append_final:
    - RUN python3 -m pip install --no-cache-dir -r /tmp/pip_requirements.txt
    - RUN python3 -m pip show infoblox-client
    - RUN ansible --version
    - RUN mkdir -p /usr/share/ansible/collections
    - RUN ANSIBLE_COLLECTIONS_PATH=/usr/share/ansible/collections ansible-doc -t inventory infoblox.nios_modules.nios_inventory
